application:
  port: 8000
  hmac_secret: "Lorem ipsum dolor sit amet, qui minim labore adipisicin"
database:
  host: "localhost"
  port: 5432
  username: "postgres"
  password: "password"
  database_name: "newsletter"
  require_ssl: false
email_client:
  base_url: "localhost"
  sender_email: "test@gmail.com"
  authorization_token: "337d0cfb705f7d1db093175c917a8e6f-6b161b0a-9df1edab"
  timeout_milliseconds: 10000
